# Generated by Django 5.0.4 on 2024-04-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField()),
                ('fav_book', models.TextField()),
                ('cur_book', models.TextField()),
                ('fav_author', models.TextField()),
                ('fav_genres', models.TextField()),
                ('public', models.BooleanField(default=False)),
            ],
        ),
    ]
