# Generated by Django 5.0.4 on 2024-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='bio',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='cur_book',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_author',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_book',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_genres',
            field=models.TextField(default=None),
        ),
    ]
