# Generated by Django 5.0.4 on 2024-04-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_memberprofile_bio_alter_memberprofile_cur_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='cur_book',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_book',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='fav_genres',
            field=models.TextField(blank=True),
        ),
    ]
