# Generated by Django 5.0.4 on 2024-04-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_memberprofile_bio_alter_memberprofile_cur_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='bio',
            new_name='profile_description',
        ),
    ]
