# Generated by Django 5.0.4 on 2024-04-30 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
