# Generated by Django 5.0.4 on 2024-05-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_savebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savebook',
            name='book',
        ),
    ]
