# Generated by Django 5.0.4 on 2024-05-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_savebook_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savebook',
            old_name='user',
            new_name='book',
        ),
    ]
