# Generated by Django 5.0.4 on 2024-06-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cost',
        ),
    ]
