apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store-app-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JoeMuldowney/devops-pipeline.git'
    targetRevision: cart
    path: manifest
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true