# Generated by Django 5.0.4 on 2024-04-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_description', models.TextField(max_length=225)),
                ('title', models.CharField(max_length=45)),
                ('genre', models.CharField(max_length=25, null=True)),
                ('year', models.DateField()),
                ('stock', models.IntegerField()),
                ('rented', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('buy_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField(max_length=225)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
