# Generated by Django 5.0.4 on 2024-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='release_date',
        ),
    ]
