# Generated by Django 5.0.4 on 2024-05-09 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_year_book_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='release_date',
        ),
    ]
