# Generated by Django 5.0.4 on 2024-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
