# Generated by Django 5.0.4 on 2024-05-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rented',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
