# Generated by Django 5.0.4 on 2024-05-10 21:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_rented_remove_book_sold_remove_book_year'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books_data', django.db.models.manager.Manager()),
            ],
        ),
    ]
