# Generated by Django 5.0.4 on 2024-05-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
