# Generated by Django 5.0.4 on 2024-05-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='author_id',
        ),
    ]
