# Generated by Django 5.0.4 on 2024-05-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_rename_book_book_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
