# Generated by Django 5.0.4 on 2024-05-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_rename_author_id_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(max_length=1000),
        ),
    ]
